/** Listas canonicas para ficha tecnica admin (CS2). Valores custom ainda permitidos na UI. */

export type CatalogOption = {
  value: string;
  label: string;
  hint?: string;
};

export const CS2_WEAPONS: CatalogOption[] = [
  { value: "AK-47", label: "AK-47", hint: "Rifle" },
  { value: "M4A4", label: "M4A4", hint: "Rifle" },
  { value: "M4A1-S", label: "M4A1-S", hint: "Rifle" },
  { value: "AUG", label: "AUG", hint: "Rifle" },
  { value: "SG 553", label: "SG 553", hint: "Rifle" },
  { value: "FAMAS", label: "FAMAS", hint: "Rifle" },
  { value: "Galil AR", label: "Galil AR", hint: "Rifle" },
  { value: "AWP", label: "AWP", hint: "Sniper" },
  { value: "SSG 08", label: "SSG 08", hint: "Sniper" },
  { value: "SCAR-20", label: "SCAR-20", hint: "Sniper" },
  { value: "G3SG1", label: "G3SG1", hint: "Sniper" },
  { value: "MAC-10", label: "MAC-10", hint: "SMG" },
  { value: "MP9", label: "MP9", hint: "SMG" },
  { value: "MP7", label: "MP7", hint: "SMG" },
  { value: "UMP-45", label: "UMP-45", hint: "SMG" },
  { value: "P90", label: "P90", hint: "SMG" },
  { value: "PP-Bizon", label: "PP-Bizon", hint: "SMG" },
  { value: "MP5-SD", label: "MP5-SD", hint: "SMG" },
  { value: "Glock-18", label: "Glock-18", hint: "Pistola" },
  { value: "USP-S", label: "USP-S", hint: "Pistola" },
  { value: "P2000", label: "P2000", hint: "Pistola" },
  { value: "P250", label: "P250", hint: "Pistola" },
  { value: "Five-SeveN", label: "Five-SeveN", hint: "Pistola" },
  { value: "Tec-9", label: "Tec-9", hint: "Pistola" },
  { value: "CZ75-Auto", label: "CZ75-Auto", hint: "Pistola" },
  { value: "Dual Berettas", label: "Dual Berettas", hint: "Pistola" },
  { value: "Desert Eagle", label: "Desert Eagle", hint: "Pistola" },
  { value: "R8 Revolver", label: "R8 Revolver", hint: "Pistola" },
  { value: "Zeus x27", label: "Zeus x27", hint: "Equipamento" },
  { value: "Nova", label: "Nova", hint: "Escopeta" },
  { value: "XM1014", label: "XM1014", hint: "Escopeta" },
  { value: "Sawed-Off", label: "Sawed-Off", hint: "Escopeta" },
  { value: "MAG-7", label: "MAG-7", hint: "Escopeta" },
  { value: "M249", label: "M249", hint: "Metralhadora" },
  { value: "Negev", label: "Negev", hint: "Metralhadora" },
  { value: "Bayonet", label: "Bayonet", hint: "Faca" },
  { value: "Bowie Knife", label: "Bowie Knife", hint: "Faca" },
  { value: "Butterfly Knife", label: "Butterfly Knife", hint: "Faca" },
  { value: "Classic Knife", label: "Classic Knife", hint: "Faca" },
  { value: "Falchion Knife", label: "Falchion Knife", hint: "Faca" },
  { value: "Flip Knife", label: "Flip Knife", hint: "Faca" },
  { value: "Gut Knife", label: "Gut Knife", hint: "Faca" },
  { value: "Huntsman Knife", label: "Huntsman Knife", hint: "Faca" },
  { value: "Karambit", label: "Karambit", hint: "Faca" },
  { value: "M9 Bayonet", label: "M9 Bayonet", hint: "Faca" },
  { value: "Navaja Knife", label: "Navaja Knife", hint: "Faca" },
  { value: "Nomad Knife", label: "Nomad Knife", hint: "Faca" },
  { value: "Paracord Knife", label: "Paracord Knife", hint: "Faca" },
  { value: "Shadow Daggers", label: "Shadow Daggers", hint: "Faca" },
  { value: "Skeleton Knife", label: "Skeleton Knife", hint: "Faca" },
  { value: "Stiletto Knife", label: "Stiletto Knife", hint: "Faca" },
  { value: "Survival Knife", label: "Survival Knife", hint: "Faca" },
  { value: "Talon Knife", label: "Talon Knife", hint: "Faca" },
  { value: "Ursus Knife", label: "Ursus Knife", hint: "Faca" },
  { value: "Kukri Knife", label: "Kukri Knife", hint: "Faca" },
  { value: "Sport Gloves", label: "Sport Gloves", hint: "Luva" },
  { value: "Specialist Gloves", label: "Specialist Gloves", hint: "Luva" },
  { value: "Moto Gloves", label: "Moto Gloves", hint: "Luva" },
  { value: "Hand Wraps", label: "Hand Wraps", hint: "Luva" },
  { value: "Driver Gloves", label: "Driver Gloves", hint: "Luva" },
  { value: "Bloodhound Gloves", label: "Bloodhound Gloves", hint: "Luva" },
  { value: "Broken Fang Gloves", label: "Broken Fang Gloves", hint: "Luva" },
  { value: "Hydra Gloves", label: "Hydra Gloves", hint: "Luva" },
];

export const CS2_WEAR_LABELS: CatalogOption[] = [
  { value: "FN", label: "FN — Factory New", hint: "0.00 – 0.07" },
  { value: "MW", label: "MW — Minimal Wear", hint: "0.07 – 0.15" },
  { value: "FT", label: "FT — Field-Tested", hint: "0.15 – 0.38" },
  { value: "WW", label: "WW — Well-Worn", hint: "0.38 – 0.45" },
  { value: "BS", label: "BS — Battle-Scarred", hint: "0.45 – 1.00" },
];

export const CS2_RARITIES: CatalogOption[] = [
  { value: "Consumer Grade", label: "Consumer Grade", hint: "Branco" },
  { value: "Industrial Grade", label: "Industrial Grade", hint: "Azul claro" },
  { value: "Mil-Spec Grade", label: "Mil-Spec Grade", hint: "Azul" },
  { value: "Restricted", label: "Restricted", hint: "Roxo" },
  { value: "Classified", label: "Classified", hint: "Rosa" },
  { value: "Covert", label: "Covert", hint: "Vermelho" },
  { value: "Contraband", label: "Contraband", hint: "Dourado" },
  { value: "Extraordinary", label: "Extraordinary", hint: "Faca / luva" },
];

export const CS2_PATTERNS: CatalogOption[] = [
  { value: "Fade", label: "Fade" },
  { value: "Marble Fade", label: "Marble Fade" },
  { value: "Doppler", label: "Doppler" },
  { value: "Gamma Doppler", label: "Gamma Doppler" },
  { value: "Case Hardened", label: "Case Hardened" },
  { value: "Crimson Web", label: "Crimson Web" },
  { value: "Slaughter", label: "Slaughter" },
  { value: "Tiger Tooth", label: "Tiger Tooth" },
  { value: "Lore", label: "Lore" },
  { value: "Autotronic", label: "Autotronic" },
  { value: "Black Laminate", label: "Black Laminate" },
  { value: "Blue Steel", label: "Blue Steel" },
  { value: "Damascus Steel", label: "Damascus Steel" },
  { value: "Rust Coat", label: "Rust Coat" },
  { value: "Ultraviolet", label: "Ultraviolet" },
  { value: "Night", label: "Night" },
  { value: "Safari Mesh", label: "Safari Mesh" },
  { value: "Forest DDPAT", label: "Forest DDPAT" },
  { value: "Boreal Forest", label: "Boreal Forest" },
  { value: "Scorched", label: "Scorched" },
  { value: "Urban Masked", label: "Urban Masked" },
  { value: "Stained", label: "Stained" },
  { value: "Vanilla", label: "Vanilla" },
  { value: "Printstream", label: "Printstream" },
  { value: "Asiimov", label: "Asiimov" },
  { value: "Redline", label: "Redline" },
  { value: "Vulcan", label: "Vulcan" },
  { value: "Neon Rider", label: "Neon Rider" },
  { value: "Dragon Lore", label: "Dragon Lore" },
  { value: "Hyper Beast", label: "Hyper Beast" },
  { value: "Bloodsport", label: "Bloodsport" },
];

/** Floats tipicos por desgaste (atalhos). */
export const CS2_FLOAT_PRESETS: CatalogOption[] = [
  { value: "0.0001", label: "0.0001", hint: "FN baixo" },
  { value: "0.01", label: "0.01", hint: "FN" },
  { value: "0.04", label: "0.04", hint: "FN" },
  { value: "0.07", label: "0.07", hint: "FN / MW" },
  { value: "0.10", label: "0.10", hint: "MW" },
  { value: "0.15", label: "0.15", hint: "MW / FT" },
  { value: "0.18", label: "0.18", hint: "FT" },
  { value: "0.25", label: "0.25", hint: "FT" },
  { value: "0.38", label: "0.38", hint: "FT / WW" },
  { value: "0.42", label: "0.42", hint: "WW" },
  { value: "0.45", label: "0.45", hint: "WW / BS" },
  { value: "0.55", label: "0.55", hint: "BS" },
  { value: "0.75", label: "0.75", hint: "BS" },
  { value: "0.99", label: "0.99", hint: "BS alto" },
];

export function suggestFloatForWear(wearLabel: string): number | null {
  const map: Record<string, number> = {
    FN: 0.04,
    MW: 0.1,
    FT: 0.25,
    WW: 0.42,
    BS: 0.75,
  };
  return map[wearLabel] ?? null;
}
